insert into CURRENCY_EXCHANGE(id,CONVERSION_MULTIPLE,ENVIRONMENT,FROM_CURRENCY,TO_CURRENCY) values(10001,78,'', 'USD','INR');
insert into CURRENCY_EXCHANGE(id,CONVERSION_MULTIPLE,ENVIRONMENT,FROM_CURRENCY,TO_CURRENCY) values(10002,7328,'', 'AUD','INR');
insert into CURRENCY_EXCHANGE(id,CONVERSION_MULTIPLE,ENVIRONMENT,FROM_CURRENCY,TO_CURRENCY) values(10003,11278,'', 'YEN','INR');
insert into CURRENCY_EXCHANGE(id,CONVERSION_MULTIPLE,ENVIRONMENT,FROM_CURRENCY,TO_CURRENCY) values(10004,882,'', 'SRE','INR');
insert into CURRENCY_EXCHANGE(id,CONVERSION_MULTIPLE,ENVIRONMENT,FROM_CURRENCY,TO_CURRENCY) values(10005,65,'', 'WWE','INR');
insert into CURRENCY_EXCHANGE(id,CONVERSION_MULTIPLE,ENVIRONMENT,FROM_CURRENCY,TO_CURRENCY) values(10006,755,'', 'RU','INR');
insert into CURRENCY_EXCHANGE(id,CONVERSION_MULTIPLE,ENVIRONMENT,FROM_CURRENCY,TO_CURRENCY) values(10007,23378,'', 'EURO','INR');





